swagger: '2.0'
info:
  title: Innkeeper (Route Manager)
  description: |
    API for manipulating Fashion Store routes. It allows all teams to access
    and define non-wildcard paths to all relevant users in employee realm as
    well as, some service realm clients (e.g. CMS). Creation of wildcard routes
    is reserved for maintainers of this API as it requires special care.
  version: 3.0.0
host: innkeeper.host.eu
schemes:
  - https
basePath: /
securityDefinitions:
  company:
    type: oauth2
    authorizationUrl: 'https://auth.provider.com/z/XUI/#login/'
    flow: implicit
    scopes:
      routes.read: |
        Reading (listing) all the routes
      routes.write: |
        All operations on routes with strict path matching.
      routes.admin: |
        All operations on all routes, including ones with regex path matching.
paths:
  '/hosts':
    get:
      security:
        - company:
          - routes.read
      summary: Returns the list of available hosts.
  '/paths':
    post:
      security:
        - company:
          - routes.write
      summary: Creates a new path resource that belongs to the team of the creator.
    get:
      security:
        - company:
          - routes.read
      summary: A list of available paths.
  '/paths/{id}':
    get:
      security:
        - company:
          - routes.read
      summary: Information about a single path.
    patch:
      security:
        - company:
          - routes.write
      summary: Partially update a path.
  '/routes':
    get:
      security:
        - company:
          - routes.read
      summary: Returns the list of all the routes.
    post:
      security:
        - company:
          - routes.write
      summary: Creating a route with specified name.
  '/current-routes':
    get:
      security:
        - company:
          - routes.read
      summary: Returns the list of all the active routes.
  '/routes/{id}':
    get:
      security:
        - company:
          - routes.read
      summary: Information about a single route.
    patch:
      security:
        - company:
          - routes.write
      summary: Partially update a route.
    delete:
      security:
        - company:
          - routes.write
      summary: Deletes a route
      description: |
        Deleting a route is only allowed for a client that originally defined
        this route or with admin credentials.
  '/updated-routes/{timestamp}':
    get:
      security:
        - company:
          - routes.read
      summary: Returns a list of route updates after the provided timestamp.