create table "AUDITS"
(
  "AUDIT_ID" BIGSERIAL NOT NULL PRIMARY KEY,
  "USER_ID" VARCHAR NOT NULL,
  "RESOURCE" VARCHAR NOT NULL,
  "RESOURCE_ID" BIGINT NOT NULL,
  "AUDIT_TYPE" VARCHAR NOT NULL,
  "TIMESTAMP" timestamp NOT NULL,
  "ENTITY" VARCHAR NOT NULL
);
